### ISSUE TITLE
executing command  "java -jar new_CKB.jar -nationality Indian -virtual 1" keeps getting error

### ISSUE THREAD

**Issue by naufalHaidar12342** [andreabradpitto/Mentore-Group-Project#2]
Hello! I tried to execute the new_CKB.jar and i got multiple different error

First Error: invalid version number
OS: Ubuntu 22.04
Java version: Java 1.8/Java 8, using openjdk 8
![error invalid version number](https://user-images.githubusercontent.com/73435900/197639245-bc3b80a7-8044-4567-8402-699b4b6e0818.png)

Second error: java heap space
OS: Kubuntu 22.04
Java version: Java 1.8, using the same openjdk 8
![error java heap space](https://user-images.githubusercontent.com/73435900/197650857-2fe7df35-4fc8-4516-81ad-2bb6dcc7a383.png)

Third error: Unable to make protected final java.lang.Class
OS: Windows 10
Java version: Java 18
![error unable to make protected final](https://user-images.githubusercontent.com/73435900/197651002-2c31b6ea-c9f3-4e23-bdb6-d65123930fe0.png)

**Comment by andreabradpitto** [comment]
Hi,

thank you for your issue report. I am the owner of the repository, but the issue is bound to a portion of the project that has been developed by @DauletBabakhan, @AliyaArystanbek, @chetanchandc, @Vish214: perhaps they could help you or provide some insights about the errors.

**Comment by naufalHaidar12342** [comment]
Thank you! I'm willing to wait for solution. Currently, me and my friends are developing our own chatbot based on this project and this is our first time interacting with ontology, so every help we could get is really appreciated!

**Comment by andreabradpitto** [comment]
By the way, if you or your friends have any problem with the GUI portion of this code, feel free to open another issue, as I am responsible for that part & willing to try and solve any undiscovered :bug:

**Comment by chetanchandc** [comment]
Hi @naufalHaidar12342,

May I know which version of java you used?

**Comment by naufalHaidar12342** [comment]
hello! i already posted the java version above @chetanchandc , that is java version 8/java 1.8 and java 18 (on another computer)

**Comment by chetanchandc** [comment]
Sorry, I was expecting the sub-version/release number.  
Ok, In any case, did you try to downgrade/upgrade to java JDK 1.8.0_231?

**Comment by naufalHaidar12342** [comment]
just tried your advice, turns out it still produce error java.lang.OutOf MemoryError: GC overhead limit exceeded. Me and my friend encountered the same error, even when using relatively newer java version compared to java 1.8, We tried this directly on our computer, not through vm

this one i tested it with windows, running inside virtual machine (using hyper-v)
![running java -jar with java 8u231 and still failed](https://user-images.githubusercontent.com/73435900/199224412-244bf136-28b3-4c61-9a94-258573733cd3.png)

and here's my java version. turns out, JDK 1.8.0_231 officially called Java version 8u231

![proof java version 8u231 installed](https://user-images.githubusercontent.com/73435900/199224523-fe34b02c-982b-4dbb-b395-d0233d0e4a79.png)

**Comment by naufalHaidar12342** [comment]
at the moment, it seems that no matter which java version we use, the java -jar command always returning error.

is it possible for us to run the app with mentore.py, then edit the path to .owl file and add class to the ontology? if so, which .owl file we should modify through protege? 

im curious if we could run the app just fine, modify .owl file according to our requirement, without following the steps to execute java -jar all the way to run the dialogue_manager.py

**Comment by andreabradpitto** [comment]
Hi @naufalHaidar12342,

I do not know if I correctly understood what you are asking, but provided I got your reply right, I would say that yes, there is a workaround.

The GUI app features a couple of lines in `mentore.py` that may help you:

```python
class Window(QtWidgets.QMainWindow):

    ontologyPath = "ontology/CKB.owl"
    ontologyParentClass = "SchoolSubject"

    def __init__(self, parent=None):
```

Here you can specify the ontology you wish to work on, so you may adjust the ontology with Protege beforehand.
Indeed, the `GUI` branch features a copy of our ontology inside the `ontology` folder, alongside a backup of the `.owl` file itself.

I hope this helps. If I understood your question(s) wrong, do not hesitate to point it out.

**Comment by naufalHaidar12342** [comment]
thank you, @andreabradpitto ! sorry if my question is hard to understand, english is also not my first language.

yeah i think you nailed it! 

so that means, me and my team only need to interact with the `CKB.owl` inside the `ontology` folder, while myself could adjust the GUI according to our need?

if i remember correctly, the last time i tried to change the text for the GUI, the app still use the same text. i might need to try it again

**Comment by andreabradpitto** [comment]
Yes, you can change `ontology/CKB.owl` how you please, and the Qt Python GUI will read your ontology. Also, you can specify a different ontology file name/starting class by editing the 2 lines I mentioned in my previous reply.

You can change the GUI as you wish: I am not aware of any bug so far, so I hope you will have a solid base to work on.

Relative to your last assertion, it might be due to the fact that you were not aware that the GUI only reads `ontology/CKB.owl`. You now know how to change that behavior.

As a last note, I want to point out that this repository is a little particular due to the fact that our branches are implementations of different portions of a larger project, thus they are meant to be able to work independently: if you are *only* interested in the GUI and its interface with an ontology, then you just have to look at the `GUI` branch. Otherwise, you can integrate our work from different branches into your project.
Maybe we should have pulled everything into the `main` branch before turning in, but we did not thought about that at the time.

**Comment by naufalHaidar12342** [comment]
thank you for the explanation. i think you were right; the GUI itself already has the line where it will call the .owl file and i only need to work with that .owl file. my focus are kinda diverted due to numerous error faced me and my friends.

as for put everything to `main` for final project but didn't think about that before, i could relate to certain level. usually, the requirement for final project is "able to run" no matter how we store it and manage it. and so, we rushed to submit the project hahaha

to be honest, my mentor also as lecturer, is the one who introduce us to this repo, since we were given task to replicate the chatbot developed by mentore team, but to assists people who requesting for business license in Indonesia.

as for the problem i mention regarding can not change text for GUI, turns out I was wrong. just tried to change certain text and the GUI did changes the text. this time, i tried to replace the "Mentore!" from the "Welcome to Mentore!" sentence, to "Chatbot BECIKU!"

![chatbot gui managed to update the text](https://user-images.githubusercontent.com/73435900/199521258-4c84cd33-9bfb-4498-8dfa-ed2145b8cd00.png)

**Comment by andreabradpitto** [comment]
Glad that everything is fine then.
Also, remember that you can specify the selected concept for the ontology with the `ontologyParentClass` variable in `mentore.py`, so that you can work with the portion on ontology you are interested in. Of course, you can instead select the highest hierarchy concept ("Thing", if I recall correctly) and work with the whole ontology.
