### ISSUE TITLE
Possible solution for java -jar keeps getting error, regardless which java version being used

### ISSUE THREAD

**Issue by naufalHaidar12342** [andreabradpitto/Mentore-Group-Project#4]
Hello!

A friend of mine assigned to replicate the ontology part of Mentore, [Vilantino](https://github.com/VilantinoF) , discovered that conversation through terminal can be performed without executing `java -jar new_CKB.jar -nationality Indian -virtual 1` command

Turns out, when executing java -jar command and return with error, some of the files required by `test_dialogue_manager.py` are deleted. Some of these files are  `resume.csv` and `triggering_keyword.json`

Since this is recently discovered, validation from Mentore team are expected.
![Conversation through terminal](https://user-images.githubusercontent.com/73435900/200343140-ad7336c4-9e57-4083-ac55-43b09d4f5377.jpeg)

**Comment by andreabradpitto** [comment]
This is interesting. Again, I await a word from one of the original developers in order to approve this improvement or to explain why this should not be done.

That said, feel free to keep experiment and to report any new discovery.
